name: sap
channels:
  - anaconda
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.9.0
  - torchvision
  - cudatoolkit=10.2
  - numpy
  - matplotlib
  - scipy
  - tqdm
  - trimesh
  - igl
  - tensorboard
  - pip
  - pip:
    - plyfile
    - open3d
    - scikit-image
    - python-mnist
    - opencv-python
    - av
    - pykdtree
    - ipdb
